
graph TD
  subgraph subGraph7 ["AWS_Seoul_Region"]
    subgraph EAI ["EAI"]
      subgraph SAP ["운영 ERP (SAP)"]
        APC37["API_SOPRemainQty"]
        APC11["API_AvailPromtQty"]
      end
    end

  %% 다이어그램
  subgraph subGraph6 ["AWS_Seoul_Region"]
    subgraph EAI ["EAI"]
      subgraph SAP ["운영 ERP (SAP)"]
        APC37["API_SOPRemainQty"]
        APC11["API_AvailPromtQty"]
      end
    end
    subgraph Database ["Database"]
      subgraph Schema_Staging["Staging"]
        STG37["STG_SOPRemainQty"]
        STG11["STG_AvailPromtQty"]
      end
      subgraph Schema_MART ["MART"]
        MART37["MART_SOPRemainQty"]
        MART11["MART_AvailPromtQty"]
      end
      subgraph Schema_BIM ["BIM"]
        BIM37["BIM_SOPRemainQty"]
        BIM11["BIM_AvailPromtQty"]
      end
    end
  end
  subgraph subGraph8 ["AWS_Europe_Region"]
    subgraph o9 ["o9"]
      CUST37["CUST_SOPRemainQty"]
      CUST11["CUST_AvailPromtQty"]
    end
  end

  

  %% 스타일 0
  APC37 -- "API 호출<br>(process-payment)" --> STG37 -.-> CUST37
  APC11 -- "API 호출<br>(process-payment)" --> STG11 -.-> CUST11

  %% 스타일 1
  APC37 -. 핵심 데이터 변환/통합 .-> APC11

  %% 스타일 정의 (선택 사항)
  linkStyle 0 stroke:blue,stroke-width:2px;
  linkStyle 1 stroke:green,stroke-width:2px,stroke-dasharray: 5 5;
