graph LR
 
  %% 다이어그램
  subgraph subGraph6 ["AWS_Seoul_Region"]
    subgraph EAI ["EAI"]
      subgraph SAP ["운영 ERP (SAP)"]
        APICP37["API_SOPRemainQty"]
        APICP11["API_AvailPromtQty"]
        APICP35["API_CustomerPrice"]
        APICP10["API_ItemPrice"]
      end
      subgraph MES ["운영 MES"]
        MESSP12["API_LineLaborTx"]
      end
      subgraph NPD ["운영 NPD"]
        NPDCP25["API_NPDItemList"]
      end
      subgraph BW_ ["운영 BW"]
        BW_CP51["BW_ClosedSalesResult"]
        BW_CP42["BW_Currency"]
        BW_CP23["BW_CurrentSKU"]
        BW_CP49["BW_Customer_OnHand"]
        BW_CP48["BW_Customer_OrderResult"]
        BW_CP22["BW_Customer_SalesResult"]
        BW_CP19["BW_Etc"]
        BW_CP12["BW_OnHand"]
        BW_CP20["BW_Short"]
        BW_CP50["BW_Promotion_SalesResult"]
        BW_CP21["BW_SalesResult"]
        BW_CP39["BW_TargetSKU"]
      end
    end
    subgraph Database ["Database"]
      direction LR
      subgraph Schema_Staging["Staging"]
      direction TB
        STGCP37["STG_SOPRemainQty"]
        STGCP11["STG_AvailPromtQty"]
        STGCP35["STG_CustomerPrice"]
        STGCP10["STG_ItemPrice"]
        STGSP12["STG_LineLaborTx"]
        STGCP25["STG_NPDItemList"]
        STGCP51["STG_closedaccountsales"]
        STGCP42["STG_currency"]
        STGCP23["STG_currentsku"]
        STGCP49["STG_customeronhand"]
        STGCP48["STG_customerorderresult"]
        STGCP22["STG_customersalesresult"]
        STGCP19["STG_miscgoods"]
        STGCP12["STG_onhand"]
        STGCP20["STG_ordershortqty"]
        STGCP50["STG_promotionsales"]
        STGCP21["STG_salestx"]
        STGCP39["STG_skutarget"]
      end
      subgraph Schema_MART ["MART"]
      direction TB
        MRTCP37["MRT_SOPRemainQty"]
        MRTCP11["MRT_AvailPromtQty"]
        MRTCP35["MRT_CustomerPrice"]
        MRTCP10["MRT_ItemPrice"]
      end
      subgraph Schema_BIM ["BIM"]
      direction TB
        BIMCP37["BIM_SOPRemainQty"]
        BIMCP11["BIM_AvailPromtQty"]
        BIMCP35["BIM_CustomerPrice"]
        BIMCP10["BIM_ItemPrice"]
      end
    end
    subgraph BIM_AUD ["BIMATRIX_AUD"]
      BIM00["BIMATRIX_TABLE"]
    end
  end

  subgraph subGraph8 ["AWS_Europe_Region"]
    direction TB
    subgraph o9 ["o9"]
      CSTCP37["CUST_SOPRemainQty"]
      CSTCP11["CUST_AvailPromtQty"]
      CSTCP35["CUST_CustomerPrice"]
      CSTCP10["CUST_ItemPrice"]
    end
  end

  %% 스타일 0
  APICP37 ==> STGCP37
  APICP11 ==> STGCP11
  APICP35 ==> STGCP35 
  APICP10 ==> STGCP10
  MESSP12 ==> STGSP12
  NPDCP25 ==> STGCP25
  BIMCP35 ==> BIM00
  BIMCP10 ==> BIM00
  STGCP37 ==> CSTCP37
  STGCP11 ==> CSTCP11
  BW_CP51 ==> STGCP51
  BW_CP42 ==> STGCP42
  BW_CP23 ==> STGCP23
  BW_CP49 ==> STGCP49
  BW_CP48 ==> STGCP48
  BW_CP22 ==> STGCP22
  BW_CP19 ==> STGCP19
  BW_CP12 ==> STGCP12
  BW_CP20 ==> STGCP20
  BW_CP50 ==> STGCP50
  BW_CP21 ==> STGCP21
  BW_CP39 ==> STGCP39

  %% 스타일 1
  MRTCP35 -. "SDB 관리" .-> CSTCP35
  MRTCP10 -. "SDB 관리" .-> CSTCP10

  %% 스타일 2
  STGCP35 -.-> MRTCP35 -.-> BIMCP35
  STGCP10 -.-> MRTCP10 -.-> BIMCP10


  style SAP fill:#F8F9F9
  style EAI fill:#5D6D7E
  style MES fill:#F8F9F9
  style NPD fill:#F8F9F9
