graph TD
 
  %% 다이어그램
  subgraph subGraph6 ["AWS_Seoul_Region"]
    subgraph EAI ["EAI"]
      subgraph SAP ["운영 ERP (SAP)"]
        APICP37["API_SOPRemainQty"]
        APICP11["API_AvailPromtQty"]
        APICP35["API_CustomerPrice"]
      end
    end
    subgraph Database ["Database"]
      direction LR
      subgraph Schema_Staging["Staging"]
      direction TB
        STGCP37["STG_SOPRemainQty"]
        STGCP11["STG_AvailPromtQty"]
        STGCP35["STG_CustomerPrice"]
      end
      subgraph Schema_MART ["MART"]
      direction TB
        MRTCP37["MRT_SOPRemainQty"]
        MRTCP11["MRT_AvailPromtQty"]
        MRTCP35["MRT_CustomerPrice"]
      end
      subgraph Schema_BIM ["BIM"]
      direction TB
        BIMCP37["BIM_SOPRemainQty"]
        BIMCP11["BIM_AvailPromtQty"]
        BIMCP35["BIM_CustomerPrice"]
      end
    end
  end
  subgraph subGraph8 ["AWS_Europe_Region"]
    direction TB
    subgraph o9 ["o9"]
      CSTCP37["CUST_SOPRemainQty"]
      CSTCP11["CUST_AvailPromtQty"]
      CSTCP35["CUST_CustomerPrice"]
    end
  end

  

  %% 스타일 0
  APICP37 -- "API 호출<br>(process-payment)" --> STGCP37 -.-> CSTCP37
  APICP11 -- "API 호출<br>(process-payment)" --> STGCP11 -.-> CSTCP11
  APICP35 -- "API 호출<br>(process-payment)" --> STGCP35 -.-> MRTCP35 -.-> BIMCP35 

MRTCP35

  %% 스타일 1
  APICP37 -.-> APICP11
  MRTCP35 -. "SDB 관리" .-> CSTCP35


  %% 스타일 정의 (선택 사항)
  linkStyle 0 stroke:blue,stroke-width:2px;
  linkStyle 1 stroke:green,stroke-width:2px,stroke-dasharray: 5 5;
